application:
  port: 8000

database:
  host: "postgres"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false

jaeger:
  address: "jaeger"
  port: 4317