application:
  port: 8000

database:
  host: "postgres"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false

jaeger:
  address: "jaeger"
  port: 4317

email_client:
  base_url: "http://0.0.0.0:1080"
  sender_email: "maxim.shelgunov@my.games"
  timeout_seconds: 10