name: coverage

on: [push]
jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    environment: PROD
    env:
      SKIP_DB: true
      APP__DATABASE__USERNAME: postgres
      APP__DATABASE__PASSWORD: password
      APP__DATABASE__DATABASE_NAME: newsletter
      APP__DATABASE__PORT: 5432
      APP__DATABASE__HOST: postgres
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: newsletter
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup database
        run: |
          apt-get update && apt-get install -y postgresql-client
          cargo install --version=0.5.7 sqlx-cli --no-default-features --features postgres
          ./scripts/init_db.sh

      - name: Upload to coverall.io
        run: |
          cargo tarpaulin --verbose --all-features --workspace --ignore-tests --coveralls ${{ secrets.COVERALL_TOKEN }}

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
